/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzingRouteImport } from './routes/analyzing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ResultRouteImport } from './routes/result'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkspaceRouteImport } from './routes/workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzingRoute = AnalyzingRouteImport.update({
  id: '/analyzing',
  path: '/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/auth': typeof AuthRoute
  '/comparison': typeof ComparisonRoute
  '/history': typeof HistoryRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/auth': typeof AuthRoute
  '/comparison': typeof ComparisonRoute
  '/history': typeof HistoryRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/auth': typeof AuthRoute
  '/comparison': typeof ComparisonRoute
  '/history': typeof HistoryRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyzing'
    | '/auth'
    | '/comparison'
    | '/history'
    | '/result'
    | '/settings'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyzing'
    | '/auth'
    | '/comparison'
    | '/history'
    | '/result'
    | '/settings'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/analyzing'
    | '/auth'
    | '/comparison'
    | '/history'
    | '/result'
    | '/settings'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzingRoute: typeof AnalyzingRoute
  AuthRoute: typeof AuthRoute
  ComparisonRoute: typeof ComparisonRoute
  HistoryRoute: typeof HistoryRoute
  ResultRoute: typeof ResultRoute
  SettingsRoute: typeof SettingsRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzing': {
      id: '/analyzing'
      path: '/analyzing'
      fullPath: '/analyzing'
      preLoaderRoute: typeof AnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzingRoute: AnalyzingRoute,
  AuthRoute: AuthRoute,
  ComparisonRoute: ComparisonRoute,
  HistoryRoute: HistoryRoute,
  ResultRoute: ResultRoute,
  SettingsRoute: SettingsRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
